version: "3.9"
name: "airflow_simple"

services:
  web:
    container_name: airflow_webserver
    build: .
    ports:
      - "8080:8080"
    volumes:
     - ../../airflow/dags:/root/airflow/dags
     - ../../airflow/logs:/root/airflow/logs
     - ../../airflow/plugins:/root/airflow/plugins
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: bash -c "airflow webserver & airflow scheduler"